spring:
  datasource:
    driverClassName : com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3307/motocatalogdb"
    username : develop
    password : develop
  sql:
    init:
      mode: always
      encoding: UTF-8
logging:
  level:
    root: info
  file:
    name: app.log
#ファイルを切り替える
  logback:
    rollingpolicy:
      max-file-size: 1MB
mybatis:
  configuration:
    map-underscore-to-camel-case: true